openapi: 3.0.1
info:
  title: i18next-print-keys
  description:
    i18next preprocessor to print translation keys including interpolated
    values.
  x-cortex-tag: Widen/i18next-print-keys
  x-cortex-git:
    github:
      repository: Widen/i18next-print-keys
  x-cortex-owners:
    - type: GROUP
      provider: GITHUB
      name: Widen/frontend-services
    - type: SLACK
      channel: content-front-end
  x-cortex-ci-cd:
    buildkite:
      pipelines:
        - slug: i18next-print-keys
  x-cortex-groups:
    - content-cloud
    - is-dependency
  x-cortex-link:
    - url: https://github.com/Widen/i18next-print-keys/blob/master/README.md
      type: Documentation
      name: Project Documentation
  x-cortex-orca-query:
    - name: Query for vulnerability dashboard in cortex
      query: |
        {
          "query": {
            "models": ["VulnerabilityV2"],
            "type": "object_set",
            "with": {
              "operator": "and",
              "type": "operation",
              "values": [
                {
                  "keys": ["CloudAccount"],
                  "models": ["CloudAccount"],
                  "type": "object",
                  "operator": "has",
                  "with": {
                    "key": "Name",
                    "values": ["AWS - 546349603759 - Cloud Data"],
                    "type": "str",
                    "operator": "in"
                  }
                },
                {
                  "keys": ["Inventory"],
                  "models": ["Inventory"],
                  "type": "object",
                  "operator": "has",
                  "with": {
                    "key": "Tags",
                    "values": ["api"],
                    "type": "str",
                    "operator": "in",
                    "at_key": "service_type"
                  }
                }
              ]
            }
          }
        }
